export const PREAPPOINTMENT_ADD_ITEM = 'PREAPPOINTMENT_ADD_ITEM'
export const PREAPPOINTMENT_REMOVE_ITEM = 'PREAPPOINTMENT_REMOVE_ITEM'
export const PREAPPOINTMENT_SAVE_SHIPPING_ADDRESS = 'PREAPPOINTMENT_SAVE_SHIPPING_ADDRESS'