export const STAFF_LIST_REQUEST = 'STAFF_LIST_REQUEST'
export const STAFF_LIST_SUCCESS = 'STAFF_LIST_SUCCESS'
export const STAFF_LIST_FAIL = 'STAFF_LIST_FAIL'


export const STAFF_DETAILS_REQUEST = 'STAFF_DETAILS_REQUEST'
export const STAFF_DETAILS_SUCCESS = 'STAFF_DETAILS_SUCCESS'
export const STAFF_DETAILS_FAIL = 'STAFF_DETAILS_FAIL'

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDER_REQUEST'
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDER_SUCCESS'
export const FETCH_ORDERS_FAIL = 'FETCH_ORDER_FAIL'

export const EDIT_DETAIL_REQUEST = 'EDIT_DETAIL_REQUEST'
export const EDIT_DETAIL_SUCCESS = 'EDIT_DETAIL_SUCCESS'
export const EDIT_DETAIL_FAIL = 'EDIT_DETAIL_FAIL'

export const CHECK_MEDICAL_REQUEST = 'CHECK_MEDICAL_REQUEST'
export const CHECK_MEDICAL_SUCCESS = 'CHECK_MEDICAL_SUCCESS'
export const CHECK_MEDICAL_FAIL = 'CHECK_MEDICAL_FAIL'

//查看用户病例
export const FETCH_MEDICAL_REQUEST = 'FETCH_MEDICAL_REQUEST'
export const FETCH_MEDICAL_SUCCESS = 'FETCH_MEDICAL_SUCCESS'
export const FETCH_MEDICAL_FAIL = 'FETCH_MEDICAL_FAIL'